name: NodeJS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  update-plurimath-submodule:
    runs-on: ubuntu-latest

    steps:
      - run: |
          cd vendor/plurimath
          git checkout ${{ github.event.client_payload.branch || 'main' }}
          cat lib/plurimath/version.rb
          echo "echoed version"

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        cat vendor/plurimath/lib/plurimath/version.rb
        npm run test:js
