name: Build and Deploy GH Pages
on:
  push:
    branches:
      - master
jobs:
  pages:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Run Podman container to build demo
        run: npm run build; mkdir gh-pages; cd gh-pages; cp -a ../demo.html ../dist/ .
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: gh-pages # The folder the action should deploy.
